services:
  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run
    profiles:
      - cf
    env_file:
      - .env
    networks:
      - internal_network

# Cloudflare DNSのProxy(Tunnelではない)を使う場合は、厳格(フル)SSLモードにすること。
# フレキシブルだと308リダイレクトループになる。
  web:
    image: caddy:2
    profiles:
      - proxy
    #environment:
    ## 検証用。本番環境のLet's Encryptを実行すると526エラーで1時間待たされることがあるため。
    #  ACME_CA: "https://acme-staging-v02.api.letsencrypt.org/directory"
    #ports:
    #  - "80:80"
    #  - "443:443"
    #  - "443:443:udp" # QUIC/HTTP3用
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped
    networks:
      - internal_network

  mi:
    image: misskey/misskey:2025.12.2
    mem_limit: 1g
    memswap_limit: 1g
    cpus: "1.5"
    environment:
      NODE_OPTIONS: "--max-old-space-size=768"
    depends_on:
      - db
      - redis
    volumes:
      - ./misskey/config.yml:/misskey/.config/default.yml:ro
      - misskey-files:/misskey/files
    restart: unless-stopped
    networks:
      - internal_network

  db:
    image: groonga/pgroonga:4.0.5-alpine-18
    #共有メモリ不足でVacuumの失敗を防止する。チューニングと合わせて変更すること。
    #shm_size >= shared_buffers。shared_buffers ≈ 総メモリの25%。
    shm_size: "512m"
    mem_limit: 1g
    memswap_limit: 1g
    cpus: "1"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./postgresql/db-init.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20
    restart: unless-stopped
    networks:
      - internal_network

  redis:
    restart: unless-stopped
    image: redis:8-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}",]
    volumes:
      - redis-data:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20
    networks:
      - internal_network

volumes:
  postgres-data:
  redis-data:
  misskey-files:
  caddy-data:
  caddy-config:

networks:
  internal_network:
